### ISSUE TITLE
unable to access phone input in the current version

### ISSUE THREAD

**Issue by hiranj-kotak** [sunarya-thito/shadcn_flutter#10]

**Comment by hiranj-kotak** [comment]
hey it would be great if you let me contribute to this package with you

**Comment by sunarya-thito** [comment]
phone input is currently in master branch and it is not available in the latest pub version yet, 
but if you wish to use it right now, you can depend on the master branch, see this guide: https://dart.dev/tools/pub/dependencies#git-packages

**Comment by sunarya-thito** [comment]
> hey it would be great if you let me contribute to this package with you

what kind of contribution are you willing to offer?

**Comment by hiranj-kotak** [comment]
i have seen there are many modules that are under dev 
i will help you creating those modules

**Comment by sunarya-thito** [comment]
> i have seen there are many modules that are under dev i will help you creating those modules

what do you mean by creating those modules?

**Comment by hiranj-kotak** [comment]
i have seen that components like table, chart are not built yet so i am willing to contribute for the same

**Comment by sunarya-thito** [comment]
> i have seen that components like table, chart are not built yet so i am willing to contribute for the same

oh you don't have to, its already on progress, its just not yet available to use
