### ISSUE TITLE
unable to locate asset entry in pubspec.yaml "Redix Icons"

### ISSUE THREAD

**Issue by HDonDev** [sunarya-thito/shadcn_flutter#11]
Hi, 
Thank for your amazing work, I'm trying to use the library in my project, and I've installed it via CLI tool, but this error keeps appearing:
`Error: unable to locate asset entry in pubspec.yaml: "packages/shadcn_flutter/icons/RadixIcons.otf".
Failed to compile application.`

P.S: I pressed enter by accident before I even typed the issue.

**Comment by sunarya-thito** [comment]
please attach your pubspec.yml

**Comment by sunarya-thito** [comment]
Update your shadcn_flutter version, the latest one is 0.0.17
(See changelog to see whats new https://pub.dev/packages/shadcn_flutter/changelog)

**Comment by sunarya-thito** [comment]
I noticed that you were using CLI to install the dependency.
It seems that the CLI installed an older version of it. Perhaps one of your dependencies uses outdated package version?

**Comment by HDonDev** [comment]
Thank you so much, It's weird how it downloaded an old version.
Please keep up the great work, this package is amazing.

**Comment by HDonDev** [comment]
> I noticed that you were using CLI to install the dependency. It seems that the CLI installed an older version of it. Perhaps one of your dependencies uses outdated package version?

I've check `flutter pub outdated` it seems that flutter_lints is outdated but I don't if it might case such issue.

anyway it seems that it's a problem on my side either ways thank you for your hard work.
