### ISSUE TITLE
 Improving the mobile experience

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#13]
On touchscreen devices, there is a lack of interaction with components. It is not clear whether a particular component was pressed or not.

I suggest adding a touch effect to all clickable components, the same as when hovering with the mouse cursor (on focus).

I also noticed that some gestures do not work on touchscreen devices, for example, hiding Toast by swiping.

**Comment by sunarya-thito** [comment]
I'll see what I can do.
My plan right now for mobile UX:
* scale down on tap down
* feedback sound on tap
* add onLongPress param on clickable/button

Also tested the toast swiping on an android device, the toast hides when i swipe it, did i miss something? is there something else i should know about this?

**Comment by sunarya-thito** [comment]
Hmm, i'll take a look at this toast issue.
For mobile adaptation, you can see the progress here: https://github.com/users/sunarya-thito/projects/1/views/1

**Comment by sunarya-thito** [comment]
Just wanted to confirm, whats the version of shadcn_flutter in your pubspec.yml?
