### ISSUE TITLE
OverflowMarquee animation issue

### ISSUE THREAD

**Issue by VenceslavZlatev** [sunarya-thito/shadcn_flutter#134]
I have a selected button and in this button i have a text as a widget and then i put OverflowMarquee onto this text widget and upon hovering with the mouse it resets strangely the animation:

here is a video: 

https://github.com/user-attachments/assets/ca831ad9-1015-4228-9d4f-33f74527aa26

**Comment by sunarya-thito** [comment]
Can you post a simple reproducible code?

**Comment by VenceslavZlatev** [comment]
> Can you post a simple reproducible code?

I think its happening because of the setstate which i have onHover:

SelectedButton(
        value: isSelected(),
        onChanged: (value) {}
         
        onHover: (value) => setState(() => isHovered = value),
        child: SizedBox(
          height: 20,
          child: Expanded(
                  child: OverflowMarquee(child: Text(widget.role.roleName))))
