### ISSUE TITLE
Month and Year will be selectable.

### ISSUE THREAD

**Issue by nhtberk** [sunarya-thito/shadcn_flutter#16]
I think you can add clcikable year and month section. Its hard to select birthdate or future date.

![image](https://github.com/user-attachments/assets/580a474c-31e1-4ee8-9412-28bf2f7d0c91)

**Comment by nhtberk** [comment]
How can i disabled dates after DateTime.now()?

**Comment by sunarya-thito** [comment]
> How can i disabled dates after DateTime.now()?

There's dateStatebuilder param in the date picker, you can decide whether a date is enabled or disabled. It is not yet released and only available in experimental version.

**Comment by nhtberk** [comment]
ok, Thank you!
