### ISSUE TITLE
Customize the style of each component from the theme

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#18]
I don't know if there is such a thing here, but in [forui](https://forui.dev/docs/themes#customize-themes) I saw the ability to customize the style of each component directly from the application theme. In addition, there is also the ability to override the style when creating a component.

I understand that this work is very difficult, but I would like to see something like this here. I hope I did not overload you with tasks)

**Comment by sunarya-thito** [comment]
I'm gonna mark this as stale until the [dart macros](https://dart.dev/language/macros) feature is finally released on the stable channel. Without it, all of the 71 components would create such a huge boilerplate code in the package.

**Comment by sunarya-thito** [comment]
Actually i'm gonna try to use [freezed](https://pub.dev/packages/freezed) to see if it's possible.

**Comment by sunarya-thito** [comment]
Closing this in favor of #98 and few other more theme data issues
