### ISSUE TITLE
Stopping carousel when scrolling fast

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#24]
The version of the carousel implemented in the library is slightly different from the original. When scrolling through several elements, the carousel first stops and only then moves to the element.

https://github.com/user-attachments/assets/929789d3-5b47-45d3-ba03-0c492747c0d8

I suggest adding the ability to customize this parameter so that you can achieve the result as in the [original version](https://ui.shadcn.com/docs/components/carousel).
I would also like to see the ability to turn off auto-scrolling of elements.

**Comment by sunarya-thito** [comment]
auto-scrolling as in auto-play? or disable drag velocity? or disable drag completely?

**Comment by sunarya-thito** [comment]
IIRC carousel will scroll automatically when the duration or durationBuilder parameter is passed, so if its null, it should not auto scroll. Unless it still auto-scrolls then its an unexpected behavior.

Also noticed the ambiguity of autoplayDuration, when it should be autoplaySpeed, might change this later.
