### ISSUE TITLE
Problems with Input on mobile

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#32]
I tried to enable the useNativeContextMenu item in Input, however this option did not work and the native menu was not enabled.

Here is my code:
```
const TextField(
   useNativeContextMenu: true,
   placeholder: 'Enter your name',
)
```

![image](https://github.com/user-attachments/assets/e0ec0b1e-ab3f-41b1-a58d-2b7baff76412)

I also noticed some problems with the context menu functions:
- select all function does not work
- when you select any function in the menu, the keyboard is hidden, which is very inconvenient when working with text

https://github.com/user-attachments/assets/65d8f2c7-eb14-4d14-9c0e-78768d022b99

**Comment by sunarya-thito** [comment]
I have pushed a commit, can you check again?
