### ISSUE TITLE
Adding a safe zone to the App Bar

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#33]
I like the new App Bar element, but how can I  padding status bar. Now it looks like this:

![image](https://github.com/user-attachments/assets/c25cfbca-ffcd-4ca5-8485-4e7fd5e59586)

I would like to achieve an effect like in Material 3, so that the status bar is filled with the same color as the app bar:
![image](https://github.com/user-attachments/assets/c188be88-7570-4a03-b967-98b1a3b04f79)

Also I think on mobile devices the padding should be reduced or made responsive because right now it looks too big

**Comment by sunarya-thito** [comment]
You need to wrap it with [SafeArea](https://api.flutter.dev/flutter/widgets/SafeArea-class.html)
I'll see what i can do with the padding
