### ISSUE TITLE
Incorporating blur into other elements

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#35]
In a recent update I noticed that you added blur to the App Bar component. This is a good solution and it looks great. I want to suggest a few more additions for this direction:

- add the ability to use blur in other components, namely Dialog, Drawer, Alert Dialog, Toast, Select, Navigation Menu, Popover, Sheet, Dropdown Menu, Navigation Bar (in the future), as well as in other interfaces that are displayed on top of other content (context menu in Input, File Picker, Time Picker, etc.)
- make the ability to turn on / off blur for each supported element separately and globally in the theme for all
- make a blur level setting in each supported element and globally in the theme for all
- make some kind of [material analogue](https://chrisbanes.github.io/haze/materials/) or blending setting (alpha) and make the setting in supported elements or globally in the theme for all
- add a layered widget for custom elements that will blur the background using theme parameters or passed parameters

I understand that this is a bit beyond the scope of the original theme, but it would not hurt. Blur can be turned off by default in the theme. In this case, normal colors will be used.

**Comment by sunarya-thito** [comment]
I'll see what i can do with the barrier color, I maybe able to clip the barrier with the container.
