### ISSUE TITLE
 Padding before the title if there is no leading

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#38]
I was going to use the App Bar without a leader, but in this case there is a void in front of the title. Even if I set left padding to 0, the situation won't change much. If there is no leading, then the padding on the left and right is different.

![image](https://github.com/user-attachments/assets/397d858a-b175-4d29-89e5-7d0ca2f1ee4a)

```
 AppBar(
            padding: EdgeInsets.only(left: 0, top: MediaQuery.of(context).padding.top + 8, right: 0, bottom: 8),
            title: const Text('Counter App'),
            trailing: [
              GhostButton(
                onPressed: () {},
                density: ButtonDensity.icon,
                child: const Icon(Icons.search),
              ),
              GhostButton(
                onPressed: () {},
                density: ButtonDensity.icon,
                child: const Icon(Icons.add),
              ),
            ]
)
```

**Comment by sunarya-thito** [comment]
I don't think this is the case anymore in the latest commit, can you check?
