### ISSUE TITLE
 Active indicator is not rounded at LinearProgressIndicator

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#41]
If I try to increase the minHeight of the LinearProgressIndicator, then the Active indicator does not have rounded borders:

![image](https://github.com/user-attachments/assets/4a9059de-d4e8-4982-923c-86acfe10e1f7)

**Comment by sunarya-thito** [comment]
`LinearProgressIndicator` was never meant to have border radius, it is used as the scaffold page loading progress. If you're looking for the one that applies the shadcn/ui design, I'd suggest to use [progress](https://sunarya-thito.github.io/shadcn_flutter/#/components/progress) instead.
