### ISSUE TITLE
InputOTP values are wrong

### ISSUE THREAD

**Issue by nhtberk** [sunarya-thito/shadcn_flutter#51]
![image](https://github.com/user-attachments/assets/e73d79e1-2082-4080-98d1-f83b6ffc10bc)

i printed the values in onchange function and its look like => [55, 53, 54, 54, 53, 57] not ( [7,5,6,6,5,9] or 756659 )

**Comment by sunarya-thito** [comment]
its codepoints, not the value. You need to convert the codepoints into String.
```
InputOTP(
    onChanged: (value) {
        print(value.otpToString());
    }
)
```

**Comment by nhtberk** [comment]
Thank you! Sorry about it.
