### ISSUE TITLE
Improvements for Navigation Bar and Rail

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#53]
I tried the new Navigation Bar and Rail components and noticed some issues:

- When adding multiple icons there is a rendering issue.
![image](https://github.com/user-attachments/assets/3ec22cf5-3a0e-444f-a094-0acece72c3a4) 
![image](https://github.com/user-attachments/assets/1ab08cda-c20d-4a57-ad26-bdb37ecc6ca1)

- Do the elements seem too big to you? I think they look too bulky and I would stick to the Material 3 or [forui](https://forui.dev/docs/bottom-navigation-bar) sizes.

- Also, there is a lack of customization for NavigationButton. You can add modes to always show the label, hide it completely (NavigationLabelType.none not work) or show it only for the selected element. I would like to achieve a similar visual with customizations.

![image](https://github.com/user-attachments/assets/1b796ff7-249c-4261-b4c0-2a60d6b96f43)

- I tried adding NavigationBar as a child and as a footer, but in neither case there is a safe area. Rail also suffers from this problem.

- I would add full-area placement to NavigationAlignment so that you can make the icons spread evenly across the available area (as it is implemented in Material).

**Comment by sunarya-thito** [comment]
> I also suggest adding a NavigationLabel setting to NavigationSidebar. Will it be floating or will it hide when scrolling, like all the other buttons. In NavigationButton, you can add a text setting when it is too long, will it scroll or just end with an ellipsis. I also noticed a gap of a few pixels between NavigationLabel, as well as when scrolling the text
> 
> ![image](https://private-user-images.githubusercontent.com/96193346/357788627-b3df817d-8f38-40eb-8e8c-6e05d358d396.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTg4MTIsIm5iZiI6MTcyMzY1ODUxMiwicGF0aCI6Ii85NjE5MzM0Ni8zNTc3ODg2MjctYjNkZjgxN2QtOGYzOC00MGViLThlOGMtNmUwNWQzNThkMzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE4MDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNGUwOTJmNTFjMjI3YTYyYTZiZmIzZjI5ZDNkMDI4ZmQxMGM5YmU2MDAxZGU3ZjgyMzRkMGU5ZGE5NWUzMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rKJGkj0NuA5uUPELcjrtCuLOYCYp3HJKf0jrt3NPU9o)

I fixed the issue with the marquee overflow component, but the other one is just really [a flutter antialiasing issue](https://github.com/flutter/flutter/issues/14288)

**Comment by sunarya-thito** [comment]
> > Set the `expands` to `true` for this case, it will expand the button to fit the remaining space.
> 
> I would like to keep the container square with the same aspect ratio. If I set expands to true, the container becomes rectangular

I added `marginAlignment` to the `NavigationButton`. Set the `expands` in the `NavigationBar` to `true` and `marginAlignment` in the `NavigationButton` to `Alignment.center`
