### ISSUE TITLE
Add padding to floatingHeader and floatingFooter

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#57]
When using floatingHeader and floatingFooter, it is important that the content is behind them, but at the same time has the necessary margins when scrolling completely up or completely down. This can be achieved by adding paddings to the scroll element. You need to add transfer of padding for the child element. If possible, I would like to see an implementation where it would not be necessary to transfer this padding to all child elements. For example, the child element can be wrapped in Scaffold and the padding from the main screen would be transferred there.

**Comment by sunarya-thito** [comment]
floatingHeader and floatingFooter work this way intentionally. If you're looking for a way to make the child of scaffold scrolls behind the floatingHeader/footer, you need to set the scrollview clip to `Clip.none` and set the `floatingHeader` and `floatingFooter` to `false`. The scaffold is designed to render the child first and then header and footer, this way you can achieve the scrolling behind app bar.

**Comment by sunarya-thito** [comment]
You can increase the [cacheExtent](https://api.flutter.dev/flutter/widgets/ScrollView/cacheExtent.html) by a few pixels to avoid the issue.

**Comment by sunarya-thito** [comment]
Another alternative would be to have a fixed-size appbar, then insert your padding with the fixed size defined for the appbar to your listview. Or you can use NestedScrollView with SliverPersistentHeader or maybe CustomScrollView. Those two are the alternatives so far. In the meantime, I'm gonna try to figure out a way to pass the app bar layout data to the child component.

**Comment by sunarya-thito** [comment]
I added `ScaffoldHeaderPadding` and `ScaffoldFooterPadding` which you can add to your ListView to add padding with size depending on your header/footer size. 
This is the rough example:
```dart
    return Scaffold(
        floatingHeader: true,
        floatingFooter: true,
        headers: [
          AppBar(
            title: const Text('Counter App'),
            subtitle: const Text('A simple counter app'),
            surfaceOpacity: 0.2,
            leading: [
              GhostButton(
                onPressed: () {
                  openDrawer(
                    context: context,
                    builder: (context) {
                      return Container(
                        alignment: Alignment.center,
                        constraints: const BoxConstraints(
                          maxWidth: 300,
                        ),
                        child: const Text('Drawer'),
                      );
                    },
                    position: OverlayPosition.left,
                  );
                },
                density: ButtonDensity.icon,
                child: const Icon(Icons.menu),
              ),
            ],
            trailing: [
              GhostButton(
                density: ButtonDensity.icon,
                onPressed: () {
                  openSheet(
                    context: context,
                    builder: (context) {
                      return Container(
                        alignment: Alignment.center,
                        constraints: const BoxConstraints(
                          maxWidth: 200,
                        ),
                        child: const Text('Sheet'),
                      );
                    },
                    position: OverlayPosition.right,
                  );
                },
                child: const Icon(Icons.search),
              ),
            ],
          ),
          const Divider(),
        ],
        footers: [
          const Divider(),
          if (_selected == 1)
            Container(
              color: Colors.purple,
              height: 30,
            ),
          NavigationBar(
            surfaceOpacity: 0.2,
            onSelected: (i) {
              setState(() {
                _selected = i;
              });
            },
            index: _selected,
            children: [
              _buildButton('Home', Icons.home),
              _buildButton('Explore', Icons.explore),
              _buildButton('Library', Icons.library_music),
            ],
          ),
        ],
        child: Container(
          color: Colors.red,
          child: ListView(
            children: [
              const ScaffoldHeaderPadding(),
              for (int i = 0; i < 50; i++)
                OutlinedContainer(
                  child: Text('Item $i'),
                ),
              const ScaffoldFooterPadding(),
            ],
          ),
        ));
```

**Comment by sunarya-thito** [comment]
can you give an example?

**Comment by sunarya-thito** [comment]
> So far I have achieved the desired effect using this code, but it seems to me that there is an easier option
> 
> ```
>   @override
>   Widget build(BuildContext context) {
>     return CustomScrollView(
>       slivers: [
>         const SliverToBoxAdapter(
>           child: ScaffoldHeaderPadding(),
>         ),
>         SliverPadding(
>             padding: const EdgeInsets.all(12),
>             sliver: SliverGrid(
>               gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
>                 crossAxisCount: 2,
>                 crossAxisSpacing: 10,
>                 mainAxisSpacing: 0,
>               ),
>               delegate: SliverChildBuilderDelegate(
>                 (BuildContext context, int index) {
>                   return CardImage(...);
>                 },
>                 childCount: 20,
>               ),
>             )),
>         const SliverToBoxAdapter(
>           child: ScaffoldFooterPadding(),
>         )
>       ],
>     );
>   }
> ```

I think this should be the final answer to your question since a Scaffold with a floating header and footer cannot magically add padding to your scrollable viewport. ScaffoldHeaderPadding and ScaffoldFooterPadding listen to layout changes, so it resizes automatically when your header/footer is resized. I'm not sure what else would be a better approach than this one.
