### ISSUE TITLE
Base64 Images

### ISSUE THREAD

**Issue by nhtberk** [sunarya-thito/shadcn_flutter#61]
Can we use the avatar with base64 string? There is a photoUrl. How can i use the base64 string in avatar?

**Comment by sunarya-thito** [comment]
I replaced `photoUrl` with `provider` in `0.0.20`, so you can either use [`NetworkImage`](https://api.flutter.dev/flutter/painting/NetworkImage-class.html) with [this method](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) or parse base64 into Uint8List and pass it to [`MemoryImage`](https://api.flutter.dev/flutter/painting/MemoryImage-class.html)

**Comment by nhtberk** [comment]
Thank you!
