### ISSUE TITLE
Twitching Color Picker

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#65]
If you quickly move the cursor around the palette, you can see how the Color Picker container twitches, as well as the dialog. I understand that this is implemented to take up only the necessary space and it is determined by the size of the content. But maybe it would be worth fixing this problem. She's not particularly important, but she's not pleasing to the eye.

https://github.com/user-attachments/assets/22253895-8b05-4543-ad95-e76eb2eb9d97

**Comment by sunarya-thito** [comment]
> I understand that this is implemented to take up only the necessary space and it is determined by the size of the content. 
I think this was unintended and rather a bug, I ran it in debug mode and had an assertion error. I'll see what I can do.

**Comment by sunarya-thito** [comment]
Should be fine by now
