### ISSUE TITLE
Incorrect blurring of elements

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#71]
Now, when blurring the background of elements, an image outside the widget is also taken. This blurs a widget that is not yet behind a widget with a blurred background. It may be worth blurring only the image that is behind the widget with a blurred background.

**Comment by sunarya-thito** [comment]
can you provide the screenshot or the reproducible code

**Comment by cyberpwnn** [comment]
My solution was to just disable the blur when the scroll extent was 0 pixels (or max extent when your blurring a bottom bar). This also works for sliver sticky headers, hacky but its really a limitation of how flutter image filters work, along with them being tremendously slow on most platforms. Better in impeller but still not "native like" and it still wont clip like your looking for.

In fact if you look close at native ios apps (any apple made app really), you can actually see they also turn off the blur on the bar when the view is not scrolled at all, they are doing the same thing. 

If you were to clip the input image, the blur wouldnt look right on the edges, the edges would either fade to darkness on a fully bright background, OR it would mirror the edges if you did it that way. Basically there isnt really a good solution other than just disabling the blur when nothing is underneath it. Look at how the flutter cupertino widgets do it.

**Comment by cyberpwnn** [comment]
Some tweaking is required, but you can control the blur from the scroll controller with a listener. I just kinda wrote this so idk if it will work right off the bat but this is generally how you could do it. This example does call set state on the entire screen instead of using a stream to only update the appbar itself but this should get the idea across just fine

```dart
class DynamicBarBlurThing extends StatefulWidget {
  const DynamicBarBlurThing({super.key});

  @override
  State<DynamicBarBlurThing> createState() => _DynamicBarBlurThingState();
}

class _DynamicBarBlurThingState extends State<DynamicBarBlurThing> {
  late ScrollController _controller;
  bool blurring = false;

  @override
  void initState() {
    // Setup Controller & Listener
    _controller = ScrollController();
    super.initState();
    _controller.addListener(() {
      if (!_controller.hasClients) return;

      // We SHOULD be blurring if the user has scrolled down at all
      bool shouldBlur = _controller.position.pixels > 0;

      // Only change the state & rebuild if the blur state has changed
      if (shouldBlur != blurring) {
        setState(() {
          blurring = shouldBlur;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        child: CustomScrollView(
          controller: _controller,
          slivers: [
            SliverPinnedHeader(
                child: AppBar(
              title: Text("Dynamic Bar Blur"),
              // We change the surface opacity to 1 when not blurring. 
              surfaceOpacity: blurring ? 0.5 : 1.0,
              // We change the surface blur to 16 when blurring.
              surfaceBlur: blurring ? 16 : 0,
            )),
            // Add your "content" below basically
            SliverList(
                delegate: SliverChildBuilderDelegate(
                    (context, _) => Text("Scroll down to see the bar blur")))
          ],
        ),
      );
}
```
