### ISSUE TITLE
Check if the button is selected

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#73]
I want to implement different icons for navigation buttons depending on whether the button is selected or not. I would like to implement this without large structures. For example, in Material, the BottomNavigationBarItem widget has icon and activeIcon values. You can tell me how to implement it correctly or you can add additional functionality for this.

I also noticed that the label in tooltip mode does not work correctly on mobile devices and is shown when clicking on a navigation element. It seems to me that it would be more correct to make the tooltip appear when pressing the button for a long time.

**Comment by sunarya-thito** [comment]
> I also noticed that the label in tooltip mode does not work correctly on mobile devices and is shown when clicking on a navigation element. It seems to me that it would be more correct to make the tooltip appear when pressing the button for a long time.

Can you make a separate issue for this one.

> I want to implement different icons for navigation buttons depending on whether the button is selected or not. I would like to implement this without large structures. For example, in Material, the BottomNavigationBarItem widget has icon and activeIcon values. You can tell me how to implement it correctly or you can add additional functionality for this.

I hope this isn't too complicated, I made StatedWidget that overrides the widget based on the parent `Clickable` state (`Clickable` is inherited/wrapped by `Button`, `SelectedButton` `IconButton`, `Toggle`, and `NavigationButton`, so it works for all of these widgets). Example:
```dart
PrimaryButton(
  leading: const StatedWidget.map(
    states: {
      'disabled': Icon(Icons.close),
      {WidgetState.hovered, WidgetState.focused}:
          Icon(Icons.add_a_photo_rounded),
      WidgetState.hovered: Icon(Icons.add_a_photo),
    },
    child: Icon(Icons.add_a_photo_outlined),
  ),
  onPressed: () {},
  child: const StatedWidget(
    focused: Text('Focused'),
    hovered: Text('Hovered'),
    pressed: Text('Pressed'),
    child: Text('Normal'),
  ),
)
```
