### ISSUE TITLE
Tooltip does not work correctly on touch screen devices

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#74]
If you use the tooltip on mobile devices, it will be displayed directly when you touch the element. For users of touch devices, the expected logic of interaction is the appearance of the Tooltip upon a long hold. In addition, you can add tactile feedback.

https://github.com/user-attachments/assets/9c3c3daf-3cf5-4246-a8aa-f51bfe34f7f5

**Comment by sunarya-thito** [comment]
pushed a commit, is it like this?

**Comment by sunarya-thito** [comment]
pushed a new commit, can you try
