### ISSUE TITLE
Using Toast with Material App Or Material Theme

### ISSUE THREAD

**Issue by SPiercer** [sunarya-thito/shadcn_flutter#75]
Hi @sunarya-thito, first of all your package is amazing

however i only need a couple of functionalities from it such as using this sonner toast.

however i found a limitation where i have to use `ShadcnApp` in order to use this toast. and when i use it, i have to submit the Shadcn themes (colors) which contradict my design since we already made our colors and design system

is there a way i can use the toast without all of this ?

**Comment by SPiercer** [comment]
i've managed to do it by doing this in the builder

```dart
MaterialApp.router(
  debugShowCheckedModeBanner: false,
  routerConfig: appRouter.router,
  theme: MaterialTheme(Theme.of(context).textTheme).light(),
  darkTheme: MaterialTheme(Theme.of(context).textTheme).dark(),
  builder: (context, child) {
    return shad.Theme(
      data: shad.ThemeData(
        colorScheme: shad.ColorSchemes.lightOrange(),
        radius: 0.5,
      ),
      child: shad.ToastLayer(child: child!),
    );
  },
);
```

**Comment by sunarya-thito** [comment]
I'll come up with something

**Comment by sunarya-thito** [comment]
You can now wrap your scaffold or anything in between MaterialApp and your main content with [`ShadcnLayer`](https://github.com/sunarya-thito/shadcn_flutter/blob/master/lib/src/shadcn_app.dart#L443), it provides the basic necessity for this package to run within your app.
