### ISSUE TITLE
Support web

### ISSUE THREAD

**Issue by selimb86** [sunarya-thito/shadcn_flutter#77]
Hello there

First of all thank you and all contributors for this awesome package.

I just seen that it does not support web due to a `dart:io` dependency in `package:pixel_snap/src/generated/widgets.dart`.

Is there a plan or aim to support web by fixing or replacing pixel_snap ?

**Comment by sunarya-thito** [comment]
Ignore the automatic tagging, it already supports the web. The [web docs](https://sunarya-thito.github.io/shadcn_flutter/) itself built on top of Flutter. Plan to remove `pixel_snap`? after this [bug](https://github.com/flutter/flutter/issues/14288) is resolved.
