### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by AndryHTC** [sunarya-thito/shadcn_flutter#78]
I didn't see any support for i18n.

Example: how can I use the Datepicker with Italian months?

**Comment by sunarya-thito** [comment]
There is i18n support, it just currently available for English only, if you want to extend the language support, you can extend the [`ShadcnLocalizations`](https://github.com/sunarya-thito/shadcn_flutter/blob/master/lib/src/components/locale/shadcn_localizations.dart#L64) class, create a [delegate](https://github.com/sunarya-thito/shadcn_flutter/blob/master/lib/src/components/locale/shadcn_localizations.dart#L7), and pass it on to your [`ShadcnApp`](https://github.com/sunarya-thito/shadcn_flutter/blob/master/lib/src/shadcn_app.dart#L33)

**Comment by AndryHTC** [comment]
Great! Italian localization coming.

Can you add it to the guide?

**Comment by AmoonPod** [comment]
This is the code of the italian extended class:

`import 'package:shadcn_flutter/shadcn_flutter.dart';

class ItalianDelegate extends ShadcnLocalizations {
  const ItalianDelegate();
  static const ItalianDelegate delegate = ItalianDelegate();

  List<String> getMonths() {
    return [
      "Gennaio",
      "Febbraio",
      "Marzo",
      "Aprile",
      "Maggio",
      "Giugno",
      "Luglio",
      "Agosto",
      "Settembre",
      "Ottobre",
      "Novembre",
      "Dicembre"
    ];
  }

  @override
  String get abbreviatedApril => 'Apr';

  @override
  String get abbreviatedAugust => 'Ago';

  @override
  String get abbreviatedDecember => 'Dic';

  @override
  String get abbreviatedFebruary => 'Feb';

  @override
  String get abbreviatedFriday => 'Ven';

  @override
  String get abbreviatedJanuary => 'Gen';

  @override
  String get abbreviatedJuly => 'Lug';

  @override
  String get abbreviatedJune => 'Giu';

  @override
  String get abbreviatedMarch => 'Mar';

  @override
  String get abbreviatedMay => 'Mag';

  @override
  String get abbreviatedMonday => 'Lun';

  @override
  String get abbreviatedNovember => 'Nov';

  @override
  String get abbreviatedOctober => 'Ott';

  @override
  String get abbreviatedSaturday => 'Sab';

  @override
  String get abbreviatedSeptember => 'Set';

  @override
  String get abbreviatedSunday => 'Dom';

  @override
  String get abbreviatedThursday => 'Gio';

  @override
  String get abbreviatedTuesday => 'Mar';

  @override
  String get abbreviatedWednesday => 'Mer';

  @override
  String get buttonCancel => 'Annulla';

  @override
  String get buttonClose => 'Chiudi';

  @override
  String get buttonNext => 'Avanti';

  @override
  String get buttonOk => 'OK';

  @override
  String get buttonPrevious => 'Indietro';

  @override
  String get buttonReset => 'Reset';

  @override
  String get buttonSave => 'Salva';

  @override
  String get colorAlpha => 'Alpha';

  @override
  String get colorBlue => 'Blu';

  @override
  String get colorGreen => 'Verde';

  @override
  String get colorHue => 'Tonalità';

  @override
  String get colorLightness => 'Luminosità';

  @override
  String get colorPickerTabHSL => 'HSL';

  @override
  String get colorPickerTabHSV => 'HSV';

  @override
  String get colorPickerTabRGB => 'RGB';

  @override
  String get colorPickerTabRecent => 'Recenti';

  @override
  String get colorRed => 'Rosso';

  @override
  String get colorSaturation => 'Saturazione';

  @override
  String get colorValue => 'Valore';

  @override
  String get commandEmpty => 'Nessun risultato trovato.';

  @override
  String get commandSearch => 'Inserisci un comando o cerca...';

  @override
  String get datePickerSelectYear => 'Seleziona un anno';

  @override
  String get emptyCountryList => 'Nessun paese trovato';

  @override
  String formBetweenExclusively(double min, double max) {
    return 'Deve essere compreso tra ${formatNumber(min)} e ${formatNumber(max)} (escluso)';
  }

  @override
  String formBetweenInclusively(double min, double max) {
    return 'Deve essere compreso tra ${formatNumber(min)} e ${formatNumber(max)} (incluso)';
  }

  @override
  String formGreaterThan(double value) {
    return 'Deve essere maggiore di ${formatNumber(value)}';
  }

  @override
  String formGreaterThanOrEqualTo(double value) {
    return 'Deve essere maggiore o uguale a ${formatNumber(value)}';
  }

  @override
  String formLengthGreaterThan(int value) {
    return 'Deve essere almeno di $value caratteri';
  }

  @override
  String formLengthLessThan(int value) {
    return 'Deve essere al massimo di $value caratteri';
  }

  @override
  String formLessThan(double value) {
    return 'Deve essere minore di ${formatNumber(value)}';
  }

  @override
  String formLessThanOrEqualTo(double value) {
    return 'Deve essere minore o uguale a ${formatNumber(value)}';
  }

  @override
  String get formNotEmpty => 'Questo campo non può essere vuoto';

  @override
  String get formPasswordDigits => 'Deve contenere almeno una cifra';

  @override
  String get formPasswordLowercase => 'Deve contenere almeno una lettera minuscola';

  @override
  String get formPasswordSpecial => 'Deve contenere almeno un carattere speciale';

  @override
  String get formPasswordUppercase => 'Deve contenere almeno una lettera maiuscola';

  @override
  String formatDateTime(DateTime dateTime, {bool showDate = true, bool showTime = true, bool showSeconds = false, bool use24HourFormat = true}) {
    String result = '';
    if (showDate) {
      result += '${dateTime.day} ${getMonths()[dateTime.month - 1]} ${dateTime.year}';
    }
    if (showTime) {
      result += ' ${dateTime.hour}:${dateTime.minute.toString().padLeft(2, '0')}';
      if (showSeconds) {
        result += ':${dateTime.second.toString().padLeft(2, '0')}';
      }
    }
    return result;
  }

  @override
  String formatNumber(double value) {
    return value.toStringAsFixed(0);
  }

  @override
  String formatTimeOfDay(TimeOfDay time, {bool use24HourFormat = true, bool showSeconds = false}) {
    return '${time.hour}:${time.minute.toString().padLeft(2, '0')}';
  }

  @override
  String get invalidEmail => 'Email non valida';

  @override
  String get invalidURL => 'URL non valido';

  @override
  String get invalidValue => 'Valore non valido';

  @override
  Map<String, String> get localizedMimeTypes => {
    'audio/aac': 'Audio AAC',
    'application/x-abiword': 'Documento AbiWord',
    'image/apng': 'Grafica PNG Animata',
    // Continue mapping more MIME types as needed
  };

  @override
  String get menuCopy => 'Copia';

  @override
  String get menuCut => 'Taglia';

  @override
  String get menuDelete => 'Elimina';

  @override
  String get menuLiveTextInput => 'Testo in tempo reale';

  @override
  String get menuPaste => 'Incolla';

  @override
  String get menuRedo => 'Ripeti';

  @override
  String get menuSearchWeb => 'Cerca sul web';

  @override
  String get menuSelectAll => 'Seleziona tutto';

  @override
  String get menuShare => 'Condividi';

  @override
  String get menuUndo => 'Annulla';

  @override
  String get monthApril => 'Aprile';

  @override
  String get monthAugust => 'Agosto';

  @override
  String get monthDecember => 'Dicembre';

  @override
  String get monthFebruary => 'Febbraio';

  @override
  String get monthJanuary => 'Gennaio';

  @override
  String get monthJuly => 'Luglio';

  @override
  String get monthJune => 'Giugno';

  @override
  String get monthMarch => 'Marzo';

  @override
  String get monthMay => 'Maggio';

  @override
  String get monthNovember => 'Novembre';

  @override
  String get monthOctober => 'Ottobre';

  @override
  String get monthSeptember => 'Settembre';

  @override
  String get placeholderColorPicker => 'Seleziona un colore';

  @override
  String get placeholderDatePicker => 'Seleziona una data';

  @override
  String get placeholderTimePicker => 'Seleziona un orario';

  @override
  String get refreshTriggerComplete => 'Aggiornamento completato';

  @override
  String get refreshTriggerPull => 'Tira per aggiornare';

  @override
  String get refreshTriggerRefreshing => 'Aggiornamento...';

  @override
  String get refreshTriggerRelease => 'Rilascia per aggiornare';

  @override
  String get searchPlaceholderCountry => 'Cerca un paese...';

  @override
  String get timeAM => 'AM';

  @override
  String get timeHour => 'Ora';

  @override
  String get timeMinute => 'Minuto';

  @override
  String get timePM => 'PM';

  @override
  String get timeSecond => 'Secondo';

  @override
  String get toastSnippetCopied => 'Testo copiato negli appunti';
}
`

**Comment by ImanHz** [comment]
Here is the Persian delegate:

`import 'package:shadcn_flutter/shadcn_flutter.dart';

class PersianLocalizationsDelegate extends ShadcnLocalizationsDelegate {
  static const PersianLocalizationsDelegate delegate =
      PersianLocalizationsDelegate();
  const PersianLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => locale.languageCode == "fa";

  @override
  Future<ShadcnLocalizations> load(Locale locale) {
    return Future.value(const PersianShadcnLocalizations());
  }
}

class PersianShadcnLocalizations extends ShadcnLocalizations {
  const PersianShadcnLocalizations();
  static const PersianShadcnLocalizations delegate =
      PersianShadcnLocalizations();

  List<String> getMonths() {
    return [
      "ژانویه",
      "فوریه",
      "مارس",
      "آوریل",
      "مه",
      "ژوئن",
      "ژوئیه",
      "اوت",
      "سپتامبر",
      "اکتبر",
      "نوامبر",
      "دسامبر"
    ];
  }

  @override
  String get abbreviatedApril => 'آور';

  @override
  String get abbreviatedAugust => 'اوت';

  @override
  String get abbreviatedDecember => 'دسام';

  @override
  String get abbreviatedFebruary => 'فور';

  @override
  String get abbreviatedFriday => 'جمع';

  @override
  String get abbreviatedJanuary => 'ژان';

  @override
  String get abbreviatedJuly => 'ژوئ';

  @override
  String get abbreviatedJune => 'ژوئن';

  @override
  String get abbreviatedMarch => 'مار';

  @override
  String get abbreviatedMay => 'مه';

  @override
  String get abbreviatedMonday => 'دوش';

  @override
  String get abbreviatedNovember => 'نوام';

  @override
  String get abbreviatedOctober => 'اکت';

  @override
  String get abbreviatedSaturday => 'شنب';

  @override
  String get abbreviatedSeptember => 'سپت';

  @override
  String get abbreviatedSunday => 'یکش';

  @override
  String get abbreviatedThursday => 'پنج';

  @override
  String get abbreviatedTuesday => 'سه‌';

  @override
  String get abbreviatedWednesday => 'چهار';

  @override
  String get buttonCancel => 'لغو';

  @override
  String get buttonClose => 'بستن';

  @override
  String get buttonNext => 'بعدی';

  @override
  String get buttonOk => 'تأیید';

  @override
  String get buttonPrevious => 'قبلی';

  @override
  String get buttonReset => 'بازنشانی';

  @override
  String get buttonSave => 'ذخیره';

  @override
  String get colorAlpha => 'آلفا';

  @override
  String get colorBlue => 'آبی';

  @override
  String get colorGreen => 'سبز';

  @override
  String get colorHue => 'رنگ';

  @override
  String get colorLightness => 'روشنایی';

  @override
  String get colorPickerTabHSL => 'HSL';

  @override
  String get colorPickerTabHSV => 'HSV';

  @override
  String get colorPickerTabRGB => 'RGB';

  @override
  String get colorPickerTabRecent => 'اخیراً';

  @override
  String get colorRed => 'قرمز';

  @override
  String get colorSaturation => 'اشباع';

  @override
  String get colorValue => 'مقدار';

  @override
  String get commandEmpty => 'نتیجه‌ای یافت نشد.';

  @override
  String get commandSearch => 'یک فرمان وارد کنید یا جستجو کنید...';

  @override
  String get datePickerSelectYear => 'انتخاب سال';

  @override
  String get emptyCountryList => 'کشوری یافت نشد';

  @override
  String formBetweenExclusively(double min, double max) {
    return 'باید بین ${formatNumber(min)} و ${formatNumber(max)} (به‌طور انحصاری) باشد';
  }

  @override
  String formBetweenInclusively(double min, double max) {
    return 'باید بین ${formatNumber(min)} و ${formatNumber(max)} (به‌طور فراگیر) باشد';
  }

  @override
  String formGreaterThan(double value) {
    return 'باید بزرگ‌تر از ${formatNumber(value)} باشد';
  }

  @override
  String formGreaterThanOrEqualTo(double value) {
    return 'باید بزرگ‌تر یا مساوی ${formatNumber(value)} باشد';
  }

  @override
  String formLengthGreaterThan(int value) {
    return 'باید حداقل $value کاراکتر باشد';
  }

  @override
  String formLengthLessThan(int value) {
    return 'باید حداکثر $value کاراکتر باشد';
  }

  @override
  String formLessThan(double value) {
    return 'باید کوچک‌تر از ${formatNumber(value)} باشد';
  }

  @override
  String formLessThanOrEqualTo(double value) {
    return 'باید کوچک‌تر یا مساوی ${formatNumber(value)} باشد';
  }

  @override
  String get formNotEmpty => 'این فیلد نمی‌تواند خالی باشد';

  @override
  String get formPasswordDigits => 'باید حداقل یک رقم داشته باشد';

  @override
  String get formPasswordLowercase => 'باید حداقل یک حرف کوچک داشته باشد';

  @override
  String get formPasswordSpecial => 'باید حداقل یک کاراکتر خاص داشته باشد';

  @override
  String get formPasswordUppercase => 'باید حداقل یک حرف بزرگ داشته باشد';

  @override
  String formatDateTime(DateTime dateTime,
      {bool showDate = true,
      bool showTime = true,
      bool showSeconds = false,
      bool use24HourFormat = true}) {
    String result = '';
    if (showDate) {
      result +=
          '${dateTime.day} ${getMonths()[dateTime.month - 1]} ${dateTime.year}';
    }
    if (showTime) {
      result +=
          ' ${dateTime.hour}:${dateTime.minute.toString().padLeft(2, '0')}';
      if (showSeconds) {
        result += ':${dateTime.second.toString().padLeft(2, '0')}';
      }
    }
    return result;
  }

  @override
  String formatNumber(double value) {
    return value.toStringAsFixed(0);
  }

  @override
  String formatTimeOfDay(TimeOfDay time,
      {bool use24HourFormat = true, bool showSeconds = false}) {
    return '${time.hour}:${time.minute.toString().padLeft(2, '0')}';
  }

  @override
  String get invalidEmail => 'ایمیل نامعتبر است';

  @override
  String get invalidURL => 'URL نامعتبر است';

  @override
  String get invalidValue => 'مقدار نامعتبر است';

  @override
  Map<String, String> get localizedMimeTypes => {
        'audio/aac': 'صدای AAC',
        'application/x-abiword': 'سند AbiWord',
        'image/apng': 'تصویر PNG متحرک',
        // ادامه مپ MIME انواع دیگر در صورت نیاز
      };

  @override
  String get menuCopy => 'کپی';

  @override
  String get menuCut => 'برش';

  @override
  String get menuDelete => 'حذف';

  @override
  String get menuLiveTextInput => 'ورودی متن زنده';

  @override
  String get menuPaste => 'چسباندن';

  @override
  String get menuRedo => 'انجام مجدد';

  @override
  String get menuSearchWeb => 'جستجو در وب';

  @override
  String get menuSelectAll => 'انتخاب همه';

  @override
  String get menuShare => 'اشتراک‌گذاری';

  @override
  String get menuUndo => 'بازگشت';

  @override
  String get monthApril => 'آوریل';

  @override
  String get monthAugust => 'اوت';

  @override
  String get monthDecember => 'دسامبر';

  @override
  String get monthFebruary => 'فوریه';

  @override
  String get monthJanuary => 'ژانویه';

  @override
  String get monthJuly => 'ژوئیه';

  @override
  String get monthJune => 'ژوئن';

  @override
  String get monthMarch => 'مارس';

  @override
  String get monthMay => 'مه';

  @override
  String get monthNovember => 'نوامبر';

  @override
  String get monthOctober => 'اکتبر';

  @override
  String get monthSeptember => 'سپتامبر';

  @override
  String get placeholderColorPicker => 'انتخاب رنگ';

  @override
  String get placeholderDatePicker => 'انتخاب تاریخ';

  @override
  String get placeholderTimePicker => 'انتخاب زمان';

  @override
  String get refreshTriggerComplete => 'بروزرسانی تکمیل شد';

  @override
  String get refreshTriggerPull => 'بکشید برای بروزرسانی';

  @override
  String get refreshTriggerRefreshing => 'در حال بروزرسانی...';

  @override
  String get refreshTriggerRelease => 'رها کنید برای بروزرسانی';

  @override
  String get searchPlaceholderCountry => 'جستجوی کشور...';

  @override
  String get timeAM => 'صبح';

  @override
  String get timeHour => 'ساعت';

  @override
  String get timeMinute => 'دقیقه';

  @override
  String get timePM => 'عصر';

  @override
  String get timeSecond => 'ثانیه';

  @override
  String get toastSnippetCopied => 'متن به کلیپ‌بورد کپی شد';

  @override
  String get dataTableColumns => "ستون‌ها";

  @override
  String get dataTableNext => "بعدی";

  @override
  String get dataTablePrevious => "قبلی";

  @override
  String dataTableSelectedRows(int count, int total) => "$count از $total";
}
`
