### ISSUE TITLE
vscode autocomplete problem

### ISSUE THREAD

**Issue by KushagraVasal** [sunarya-thito/shadcn_flutter#82]
Is there any reason why you choose the name
TextField instead of CnTextField
Switch instead of CnSwitch.
Same name as in Flutter creates lots of issues in the vscode autocomplete.

and why Basic instead of  ListTile or CnListTile

**Comment by sunarya-thito** [comment]
I personally don't like additional prefixes in front of the class name, the package aims to replace the entire material design system, so there's no reason to use TextField from flutter anymore (it uses material design). However, you can use [library prefix](https://dart.dev/language/libraries#specifying-a-library-prefix) when importing to avoid conflict if you still want to use some part of the material design system.

> and why Basic instead of ListTile or CnListTile

ListTile's purpose is to be used inside a List view, Basic's purpose is just to provide basic content layout. Those are two diff widget tho has similar layout.
